</section>
    <section id="bottom">
        <div class="container wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <div class="row">
                  
            </div>
        </div>
    </section><!--/#bottom-->


<footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                   ITI All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li class="active"><a href="<?php echo $this->baseUrl();?>/user/list">Home</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/product/list">Products</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/user/list">Users</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/order/myorders">Manual orders</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/checks/checks">Checks</a></li> 
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->


</body>
</html>