<!-- to get data from session --!>    
<?php
    $auth = Zend_Auth::getInstance();
    $name=$auth->getIdentity()->name;
    $img=$auth->getIdentity()->picture;
    ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | Om Gamal</title>
	

   
    <link href="<?= $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/css/font-awesome.min.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/css/animate.min.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/css/prettyPhoto.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/css/main.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/css/responsive.css" rel="stylesheet">
    
    <link rel="shortcut icon" href="<?= $this->baseUrl() ?>/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?= $this->baseUrl() ?>/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?= $this->baseUrl() ?>/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?= $this->baseUrl() ?>/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="<?= $this->baseUrl() ?>/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->



<body class="homepage">

    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>       <a href="<?php echo $this->baseUrl();?>/user/logoutuser"> logout</a>
 </p></div>
                    </div>
                    <div class="col-sm-6 col-xs-8">
                       <div class="social">
                            
                            <div class="search">
                                <form role="form">
                                    <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                    <i class="fa fa-search"></i>
                                </form>
                           </div>
                       </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                     
   
              <!--      <a class="navbar-brand" href="index.html"><img  src="<?= $this->baseUrl() ?>/imagess/logo.png" alt="logo"></a> --!>

                                        <a class="navbar-brand" href="index.html"><?php echo "<img width = '70' height='70' src = '".$this->baseUrl()."/images/".$img."'/>" ;    ?> <div style="font-size: medium; font-family: fantasy; float: right; padding: auto;"><?php  echo  $name; ?></div></a><br><div> </div>
                </div>
				
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        
                        
                        
                        <li class="active"><a href="<?php echo $this->baseUrl();?>/order/index">Home</a></li>
                        
                        <li class="dropdown" id="uniq">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl();?>/product/add">Add product</a></li>
                                <li><a href="<?php echo $this->baseUrl();?>/product/list">View products</a></li>
                            </ul>
                        </li>
                        
                        <li class="dropdown" id="uniqsss">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Category <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl();?>/category/addcat">Add Category</a></li>
                                <li><a href="<?php echo $this->baseUrl();?>/category/listall">View categories</a></li>
                            </ul>
                        </li>
                        
                        <li class="dropdown" id="uniqss">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl();?>/user/user">Add user</a></li>
                                <li><a href="<?php echo $this->baseUrl();?>/user/list">View users</a></li>
                            </ul>
                        </li>
                        
                        <li><a href="<?php echo $this->baseUrl();?>/userorder/listproducts">orders</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/checks/checks" id="uniqs">Checks</a></li> 
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
		
    </header><!--/header-->
 
   <section id="feature" class="transparent-bg">
        <div class="container">
           <div class="center wow fadeInDown">
              