<div style="margin-left:90em"> 
    <?php echo '<a href = "'.$this->baseUrl().'/user/user/id/'.'"><h3> add User</h3></a> ';?>
</div>
</pre>

<table border=2" align="center">
    <tr>
        <td>Name    
        </td>
        <td>Room
            
        </td>
        <td>Image
            
        </td>
        <td>Ext
            
        </td>
        <td>Action
       .
            
        
        
    </tr>
<?php

//print_r($this->users).

for($i=0;$i< count($this->users) ;$i++){
?>    
     <tr> 
<?php
//    foreach ($this->users[$i]as $col => $va) {
//        
//       echo "<td ><br>".$va ."</td>";
//       
//    }
    

     
    
    echo "<td> ".$this->users[$i]['name']." </td>" ;
    
    echo "<td> ".$this->users[$i]['room']." </td>" ;
    echo "<td> <img width = '100' height='100' src = '".$this->baseUrl()."/images/".$this->users[$i]['picture']."'/>" ;
    
    echo "<td> ".$this->users[$i]['ext']." </td>" ;
   
    
    
   
    
    
    //echo "<td> <a href = '".$this->baseUrl()."/user/user/id/".$this->users[$i]['id']."'> add </a> |";
    echo "<td> <a href = '".$this->baseUrl()."/user/delete/id/".$this->users[$i]['id']."'> Delete </a>|"
            . "<a href = '".$this->baseUrl()."/user/edit/id/".$this->users[$i]['id']."'> Edit </a> </td>" ;
   
    
}
?>

</tr>
</table>
