<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery.js"></script>
<script>
$(function(){
    $("#header").hide();
    $("#footer").hide();
    $("#bottom").hide();
});
</script>

<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Login Form</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		
                <link href="<?= $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">
                <link href="<?= $this->baseUrl() ?>/css/styles.css" rel="stylesheet">
  
	</head>
        
<body>
<!--login modal-->
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h1 class="text-center">Login</h1>

      </div>
      <div class="modal-body">
          
          
          <?php

if(isset($this->data))
{
    
    var_dump($this->data);
}else{
    echo $this->form;

}
echo "<a href = '".$this->baseUrl()."/user/forgetpass'> Forget Pass? </a> <br/> <br/>" ;
?>
          
          
      </div>
      <div class="modal-footer">
         	
      </div>
  </div>
  </div>
</div>
	<!-- script references -->

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/bootstrap.min.js"></script>
	</body>
</html>
