
<html> 
    <head> 
        <title>Add User</title>
        

            
    </head> 
    <body> 
        
            <div id="adduser">
                <p> Add User </p>
            <?php

            if(isset($this->data))
            {
                var_dump($this->data);
            }else{
                echo $this->form;

            }
    
            ?>
           
             </div> 
        
    </body> </html>